---
title: Обработка структурированных исключений в C++
description: Обработка структурированных исключений с помощью модели C++ обработки исключений.
ms.date: 09/19/2019
helpviewer_keywords:
- structured exception handling [C++], vs. C++ exception handling
- structured exception handling [C++], vs. unstructured
- exceptions [C++], wrapper class
- C++ exception handling [C++], vs. structured exception handling
- wrapper classes [C++], C exception
ms.assetid: f21d1944-4810-468e-b02a-9f77da4138c9
ms.openlocfilehash: 0c0e458f576325034d77676d247020adedfa33e5
ms.sourcegitcommit: f907b15f50a6b945d0b87c03af0050946157d701
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 09/20/2019
ms.locfileid: "71158729"
---
# <a name="handle-structured-exceptions-in-c"></a>Обработка структурированных исключений в C++

Основное различие между структурированной обработкой исключений C (SEH C++ ) и обработкой C++ исключений заключается в том, что модель обработки исключений работает в типах, а модель обработки структурированных исключений C работает с исключениями одного типа. в частности, **целое число без знака**. То есть, исключения языка C идентифицируются целым числом без знака, тогда как исключения языка C++ идентифицируются типом данных. При возникновении структурированного исключения в C каждый возможный обработчик выполняет фильтр, который проверяет контекст исключения C и определяет, следует ли принимать исключение, передавать его другому обработчику или игнорировать. При возникновении исключения в языке C++ оно может быть любого типа.

Второе отличие заключается в том, что модель обработки структурированных исключений C называется *асинхронной*, поскольку исключения происходят во вторичном потоке управления. Механизм C++ обработки исключений является полностью *синхронным*. Это означает, что исключения происходят только при возникновении.

При использовании параметра компилятора [/EHs или/EHsc](../build/reference/eh-exception-handling-model.md) обработчики исключений не C++ обрабатывали структурированные исключения. Эти исключения обрабатываются только с помощью структурированных обработчиков исключений **__except** или обработчиков структурированного завершения **__finally** . Дополнительные сведения см. в разделе [структурированная обработка исключенийC++(C/)](structured-exception-handling-c-cpp.md).

В параметре компилятора [/EHa](../build/reference/eh-exception-handling-model.md) , если в C++ программе возникает исключение C, оно может быть обработано структурированным обработчиком исключений со связанным фильтром или C++ обработчиком **catch** , в зависимости от того, какое значение динамически близко к исключению. локального. Например, этот пример C++ программы создает исключение C внутри C++ контекста **try** :

## <a name="example---catch-a-c-exception-in-a-c-catch-block"></a>Пример. перехват исключения C в блоке C++ catch

```cpp
// exceptions_Exception_Handling_Differences.cpp
// compile with: /EHa
#include <iostream>

using namespace std;
void SEHFunc( void );

int main() {
   try {
      SEHFunc();
   }
   catch( ... ) {
      cout << "Caught a C exception."<< endl;
   }
}

void SEHFunc() {
   __try {
      int x, y = 0;
      x = 5 / y;
   }
   __finally {
      cout << "In finally." << endl;
   }
}
```

```Output
In finally.
Caught a C exception.
```

## <a name="c-exception-wrapper-classes"></a>Классы-оболочки исключений C

В простом примере, как показано выше, исключение C может быть перехвачено только многоточием ( **...** ) **перехватить** обработчик. Обработчику не передается никакая информация о типе или характере исключения. Хотя этот метод работает, в некоторых случаях может потребоваться определить преобразование между двумя моделями обработки исключений, чтобы каждое исключение C было связано с конкретным классом. Для преобразования можно определить класс-оболочку исключения C, который может использоваться или быть производным от, чтобы атрибут определенного типа класса использовался в исключении C. Таким образом, каждое исключение C может обрабатываться отдельно от конкретного C++ обработчика **catch** , а не из одного обработчика.

Класс-оболочка может иметь интерфейс, состоящий из некоторых функций-членов, которые определяют значение исключения; этот интерфейс может получать расширенные сведения о контексте исключения, предоставляемые моделью исключений языка C. Также может потребоваться определить конструктор по умолчанию и конструктор, принимающий **беззнаковый аргумент int** (для предоставления базового представления исключений C), и побитовый конструктор копирования. Ниже приведена возможная реализация класса-оболочки исключения C.

```cpp
// exceptions_Exception_Handling_Differences2.cpp
// compile with: /c
class SE_Exception {
private:
   SE_Exception() {}
   SE_Exception( SE_Exception& ) {}
   unsigned int nSE;
public:
   SE_Exception( unsigned int n ) : nSE( n ) {}
   ~SE_Exception() {}
   unsigned int getSeNumber() {
      return nSE;
   }
};
```

Чтобы использовать этот класс, установите пользовательскую функцию преобразования исключений C, которая вызывается внутренним механизмом обработки исключений каждый раз при возникновении исключения C. В функции перевода можно создать любое типизированное исключение ( `SE_Exception` возможно, тип или класс, производный от `SE_Exception`), который может быть перехвачен соответствующим C++ соответствующим обработчиком **catch** . Вместо этого функция перевода может возвращать значение, указывающее, что она не обрабатывала исключение. Если функция перевода вызывает исключение C, вызывается метод [Terminate](../c-runtime-library/reference/terminate-crt.md) .

Чтобы указать пользовательскую функцию перевода, вызовите функцию [_set_se_translator](../c-runtime-library/reference/set-se-translator.md) с именем функции перевода в качестве одного аргумента. Функция перевода, которую вы пишете, вызывается один раз для каждого вызова функции в стеке, который содержит блоки **try** . Функция перевода по умолчанию отсутствует; Если не указать его путем вызова **_set_se_translator**, то исключение C может быть перехвачено только обработчиком **catch** с многоточием.

## <a name="example---use-a-custom-translation-function"></a>Пример. Использование пользовательской функции перевода

Например, следующий код устанавливает пользовательскую функцию преобразования, а затем создает исключение языка C, которое находится в оболочке класса `SE_Exception`:

```cpp
// exceptions_Exception_Handling_Differences3.cpp
// compile with: /EHa
#include <stdio.h>
#include <eh.h>
#include <windows.h>

class SE_Exception {
private:
   SE_Exception() {}
   unsigned int nSE;
public:
   SE_Exception( SE_Exception& e) : nSE(e.nSE) {}
   SE_Exception(unsigned int n) : nSE(n) {}
   ~SE_Exception() {}
   unsigned int getSeNumber() { return nSE; }
};

void SEFunc() {
    __try {
        int x, y = 0;
        x = 5 / y;
    }
    __finally {
        printf_s( "In finally\n" );
    }
}

void trans_func( unsigned int u, _EXCEPTION_POINTERS* pExp ) {
    printf_s( "In trans_func.\n" );
    throw SE_Exception( u );
}

int main() {
    _set_se_translator( trans_func );
    try {
        SEFunc();
    }
    catch( SE_Exception e ) {
        printf_s( "Caught a __try exception with SE_Exception.\n" );
        printf_s( "nSE = 0x%x\n", e.getSeNumber() );
    }
}
```

```Output
In trans_func.
In finally
Caught a __try exception with SE_Exception.
nSE = 0xc0000094
```

## <a name="see-also"></a>См. также

[Смешивание C (структурированной) C++ и исключений](../cpp/mixing-c-structured-and-cpp-exceptions.md)
