---
description: 'Дополнительные сведения о: C28198'
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
ms.openlocfilehash: 368180985a9541e87c8a74ff912ff29c3b883e03
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/11/2020
ms.locfileid: "97168531"
---
# <a name="c28198"></a>C28198

> предупреждение C28198: возможна утечка памяти из-за исключения.

Это предупреждение означает, что выделенная память не освобождается после возникновения исключения. Инструкция в конце пути может вызвать исключение. Память была передана в функцию, которая могла сохранить копию для последующего освобождения.

Это предупреждение очень похоже на предупреждение [C28197](../code-quality/c28197.md). Здесь также можно использовать заметки, Рекомендуемые для использования с предупреждением [C28197](../code-quality/c28197.md) .

## <a name="example"></a>Пример

Следующий пример кода вызывает появление этого предупреждения.

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

Следующий пример кода позволяет избежать появления этого предупреждения.

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
